const fs = require('fs');
const path = require('path');

const avatarDir = path.join(__dirname, '../src/assets/avatar');

// Duplicates to delete explicitly
const filesToDelete = [
    '2B.webp',
    'A2.webp',
    'iDoll 썬.webp',
    'iDoll 오션.webp',
    'iDoll 플라워.webp',
    '네베.webp',
    '네온 _ 블루 오션.webp',
    '네온.webp',
    '네온_비전아이.webp',
    '라피.webp',
    '루주.webp',
    '리틀 머메이드.webp',
    '마르차나.webp',
    '마리.webp',
    '마스트_로망틱메이드.webp',
    '베스티.webp',
    '볼륨.webp',
    '소라.webp',
    '솔져 E.G..webp',
    '솔져 F.A..webp',
    '솔져 O.W..webp',
    '스노우화이트_헤비암즈.webp',
    '아니스_스타.webp',
    '아니스.webp',
    '아르카나_포츈메이트.webp',
    '아르카나.webp',
    '아리아.webp',
    '앵커_이노센트메이드.webp',
    '유니.webp',
    '크로우.webp',
    '미하라 _ 본딩 체인.webp',
    '프로덕트 08.webp',
    '프로덕트 12.webp',
    '프로덕트 23.webp',
    'tia_card.webp',
    '목단.webp'
];

// Mapping for Korean/Unformatted filenames -> Standard format (company_rarity_code.webp)
const renameMap = {
    'D _ 킬러 와이프.webp': 'e_ssr_d_killer_wife.webp',
    'D.webp': 'e_ssr_d.webp',
    'E.H..webp': 'e_ssr_eh.webp',
    'K.webp': 'e_ssr_k.webp',
    'N102.webp': 'm_sr_n102.webp',
    '그레이브.webp': 'p_ssr_grave.webp',
    '길로틴 _ 윈터 슬레이어.webp': 'e_ssr_guillotine_winter_slayer.webp',
    '길로틴.webp': 'e_ssr_guillotine.webp',
    '길티.webp': 'm_ssr_guilty.webp',
    '나가.webp': 'm_ssr_naga.webp',
    '나유타.webp': 'p_ssr_nayuta.webp',
    '네로.webp': 't_ssr_nero.webp',
    '네온 _ 비전 아이.webp': 'e_ssr_neon_vision_eye.webp',
    '노벨.webp': 'm_ssr_novel.webp',
    '노아.webp': 'p_ssr_noah.webp',
    '노이즈.webp': 't_ssr_noise.webp',
    '누아르.webp': 't_ssr_noir.webp',
    '니힐리스타.webp': 'p_ssr_nihilister.webp',
    '델타 _ 닌자 시프.webp': 'e_ssr_delta_ninja_thief.webp',
    '델타.webp': 'e_sr_delta.webp',
    '도라.webp': 't_ssr_dolla.webp',
    '도로시 _ 세렌디피티.webp': 'p_ssr_dorothy_serendipity.webp',
    '도로시.webp': 'p_ssr_dorothy.webp',
    '드레이크.webp': 'm_ssr_drake.webp',
    '디젤 _ 윈터 스위츠.webp': 'e_ssr_diesel_winter_sweets.webp',
    '디젤.webp': 'e_ssr_diesel.webp',
    '라이.webp': 't_ssr_rei.webp',
    '라푼젤 _ 퓨어 그레이스.webp': 'p_ssr_rapunzel_pure_grace.webp',
    '라푼젤.webp': 'p_ssr_rapunzel.webp',
    '라플라스 _ 얼티밋 히어로.webp': 'm_ssr_laplace_ultimate_hero.webp',
    '라플라스.webp': 'm_ssr_laplace.webp',
    '라피 _ 레드 후드.webp': 'e_ssr_rapi_red_hood.webp',
    '람.webp': 'a_sr_ram.webp',
    '레드 후드.webp': 'p_ssr_red_hood.webp',
    '레오나.webp': 't_ssr_leona.webp',
    '레이 (가칭).webp': 'a_ssr_rei.webp',
    '레이.webp': 'a_ssr_rei_alt.webp',
    '레이븐.webp': 'a_ssr_raven.webp',
    '레이블.webp': 't_ssr_rayble.webp',
    '렘.webp': 'a_ssr_rem.webp',
    '로산나 _ 시크 오션.webp': 't_ssr_rosanna_chic_ocean.webp',
    '로산나.webp': 't_ssr_rosanna.webp',
    '루드밀라 _ 윈터 오너.webp': 't_ssr_ludmilla_winter_owner.webp',
    '루드밀라.webp': 't_ssr_ludmilla.webp',
    '루마니.webp': 't_ssr_rumani.webp',
    '루피 _ 윈터 쇼퍼.webp': 't_ssr_rupee_winter_shopper.webp',
    '루피.webp': 't_ssr_rupee.webp',
    '리버렐리오.webp': 'p_ssr_liberalio.webp',
    '리타.webp': 'm_ssr_liter.webp',
    '릴리.webp': 'p_ssr_liliweiss.webp',
    '마나.webp': 'm_ssr_mana.webp',
    '마르차나 _ 마린 스터디.webp': 'e_ssr_marciana_marine_study.webp',
    '마스트 _ 로망틱 메이드.webp': 'e_ssr_mast_romantic_maid.webp',
    '마스트.webp': 'e_ssr_mast.webp',
    '마키마.webp': 'a_ssr_makima.webp',
    '맥스웰 _ 오디너리 미케닉.webp': 'm_ssr_maxwell_ordinary_mechanic.webp',
    '맥스웰.webp': 'm_ssr_maxwell.webp',
    '메어리 _ 베이 갓데스.webp': 't_ssr_mary_bay_goddess.webp',
    '메어리.webp': 't_ssr_mary.webp',
    '메이든 _ 아이스 로즈.webp': 'e_ssr_maiden_ice_rose.webp',
    '메이든.webp': 'e_ssr_maiden.webp',
    '모더니아.webp': 'p_ssr_modernia.webp',
    '모리.webp': 't_ssr_mori.webp',
    '미란다.webp': 'e_ssr_miranda.webp',
    '미사토.webp': 'a_sr_misato.webp',
    '미카 _ 스노우 버디.webp': 't_sr_mika_snow_buddy.webp',
    '미카.webp': 't_sr_mika.webp',
    '미하라.webp': 'm_sr_mihara.webp',
    '민트.webp': 't_ssr_mint.webp',
    '밀크 _ 블루밍 바니.webp': 't_ssr_milk_blooming_bunny.webp',
    '밀크.webp': 't_ssr_milk.webp',
    '바이퍼.webp': 't_ssr_viper.webp',
    '백학.webp': 't_ssr_byakko.webp',
    '베스티 _ 택티컬 업.webp': 'e_ssr_vesti_tactical_up.webp',
    '베이.webp': 't_ssr_bay.webp',
    '벨로타.webp': 't_sr_belorta.webp',
    '벨벳.webp': 't_ssr_velvet.webp',
    '브래디.webp': 't_ssr_brady.webp',
    '브리드 _ 사일런트 트랙.webp': 'e_ssr_brid_silent_track.webp',
    '브리드.webp': 'e_ssr_brid.webp',
    '블랑.webp': 't_ssr_blanc.webp',
    '비스킷.webp': 't_ssr_biscuit.webp',
    '사쿠라 (SR).webp': 't_sr_sakura.webp',
    '사쿠라 _ 블룸 인 서머.webp': 't_ssr_sakura_bloom_in_summer.webp',
    '사쿠라.webp': 't_ssr_sakura.webp',
    '센티.webp': 'm_ssr_centi.webp',
    '소다 _ 트윙클링 바니.webp': 't_ssr_soda_twinkling_bunny.webp',
    '소다.webp': 't_ssr_soda.webp',
    '솔린 _ 프로스트 티켓.webp': 'e_ssr_soline_frost_ticket.webp',
    '솔린.webp': 'e_ssr_soline.webp',
    '슈가.webp': 't_ssr_sugar.webp',
    '스노우 화이트 _ 이노센트 데이즈.webp': 'p_ssr_snow_white_innocent_days.webp',
    '스노우 화이트 _ 헤비암즈.webp': 'p_ssr_snow_white_heavy_arms.webp',
    '스노우 화이트.webp': 'p_ssr_snow_white.webp',
    '시그널.webp': 'e_ssr_signal.webp',
    '신.webp': 'm_ssr_sin.webp',
    '신데렐라 _ 크리스탈 웨이브.webp': 'p_ssr_cinderella_crystal_wave.webp',
    '신데렐라.webp': 'p_ssr_cinderella.webp',
    '아니스 _ 스타.webp': 't_ssr_anis_star.webp',
    '아니스 _ 스파클링 서머.webp': 't_ssr_anis_sparkling_summer.webp',
    '아르카나 _ 포츈 메이트.webp': 'e_ssr_arcana_fortune_mate.webp',
    '아비스타.webp': 't_ssr_avista.webp',
    '아스카 _ WILLE.webp': 'a_ssr_asuka_wille.webp',
    '아스카.webp': 'a_ssr_asuka.webp',
    '아이기스.webp': 'e_ssr_aegis.webp',
    '아인.webp': 'm_ssr_ein.webp',
    '아크레인저 블랙.webp': 'm_ssr_ark_ranger_black.webp',
    '애드미.webp': 'm_ssr_admi.webp',
    '앤 _ 미라클 페어리.webp': 'm_ssr_anne_miracle_fairy.webp',
    '앨리스 _ 원더랜드 바니.webp': 't_ssr_alice_wonderland_bunny.webp',
    '앨리스.webp': 't_ssr_alice.webp',
    '앵커 _ 이노센트 메이드.webp': 'e_ssr_anchor_innocent_maid.webp',
    '앵커.webp': 'e_sr_anchor.webp',
    '얀.webp': 't_ssr_yan.webp',
    '에밀리아.webp': 'a_ssr_emilia.webp',
    '에이다.webp': 'a_ssr_ada.webp',
    '에이드 _ 에이전트 바니.webp': 't_ssr_ade_agent_bunny.webp',
    '에이드.webp': 't_ssr_ade.webp',
    '에테르.webp': 'm_sr_ether.webp',
    '에피넬.webp': 'm_ssr_epinel.webp',
    '엑시아.webp': 'm_ssr_exia.webp',
    '엠마 _ 택티컬 업.webp': 'e_ssr_emma_tactical_up.webp',
    '엠마.webp': 'e_ssr_emma.webp',
    '유키코.webp': 'a_ssr_yukiko.webp',
    '율리아.webp': 'm_ssr_julia.webp',
    '율하.webp': 't_ssr_yulha.webp',
    '은화 _ 택티컬 업.webp': 'e_ssr_eunhwa_tactical_up.webp',
    '은화.webp': 'e_ssr_eunhwa.webp',
    '이브.webp': 'a_ssr_eve.webp',
    '이사벨.webp': 'p_ssr_isabel.webp',
    '일레그 _ 붐 앤 쇼크.webp': 'm_ssr_elegg_boom_and_shock.webp',
    '일레그.webp': 'm_ssr_elegg.webp',
    '자칼.webp': 'm_ssr_jackal.webp',
    '질.webp': 'a_ssr_jill.webp',
    '차임.webp': 'p_ssr_chime.webp',
    '츠바이.webp': 'm_ssr_zwei.webp',
    '치사토.webp': 'a_ssr_chisato.webp',
    '코코아.webp': 't_ssr_cocoa.webp',
    '쿠루미.webp': 'a_ssr_kurumi.webp',
    '퀀시 _ 이스케이프 퀸.webp': 'm_ssr_quency_escape_queen.webp',
    '퀀시.webp': 'm_ssr_quency.webp',
    '퀸(마코토).webp': 'a_ssr_queen_makoto.webp',
    '크라운.webp': 'p_ssr_crown.webp',
    '크러스트.webp': 't_ssr_crust.webp',
    '클레어.webp': 'a_ssr_claire.webp',
    '클레이.webp': 't_ssr_clay.webp',
    '키리.webp': 'e_ssr_kiri.webp',
    '킬로.webp': 'm_ssr_kilo.webp',
    '타키나.webp': 'a_ssr_takina.webp',
    '토브.webp': 'm_ssr_tove.webp',
    '트로니.webp': 'm_ssr_trony.webp',
    '트리나.webp': 't_ssr_trina.webp',
    '티아.webp': 'm_ssr_tia.webp',
    '파스칼.webp': 'a_sr_pascal.webp',
    '파워.webp': 'a_ssr_power.webp',
    '팬텀.webp': 'e_ssr_phantom.webp',
    '페퍼.webp': 'm_ssr_pepper.webp',
    '폴리.webp': 'e_ssr_poli.webp',
    '폴크방.webp': 't_ssr_folkwang.webp',
    '프리바티 _ 언카인드 메이드.webp': 'e_ssr_privaty_unkind_maid.webp',
    '프리바티.webp': 'e_ssr_privaty.webp',
    '프리카.webp': 't_ssr_frika.webp',
    '프림.webp': 't_ssr_frima.webp',
    '플로라.webp': 'm_ssr_flora.webp',
    '하란.webp': 'p_ssr_haran.webp',
    '헬름 _ 아쿠아마린.webp': 'e_ssr_helm_aquamarine.webp',
    '헬름.webp': 'e_ssr_helm.webp',
    '홍련 _ 흑영.webp': 'p_ssr_scarlet_black_shadow.webp',
    '홍련.webp': 'p_ssr_scarlet.webp',
    '히메노.webp': 'a_sr_himeno.webp'
};

// Execute deletes
filesToDelete.forEach(f => {
    const fullPath = path.join(avatarDir, f);
    if (fs.existsSync(fullPath)) {
        fs.unlinkSync(fullPath);
        console.log(`Deleted duplicate file: ${f}`);
    }
});

// Execute renames
Object.keys(renameMap).forEach(oldName => {
    const oldPath = path.join(avatarDir, oldName);
    const newName = renameMap[oldName];
    const newPath = path.join(avatarDir, newName);

    if (fs.existsSync(oldPath)) {
        // If target file already exists and is different, handle it
        if (fs.existsSync(newPath) && oldPath !== newPath) {
            console.log(`Target ${newName} already exists. Removing ${oldName}`);
            fs.unlinkSync(oldPath);
        } else {
            fs.renameSync(oldPath, newPath);
            console.log(`Renamed: ${oldName} -> ${newName}`);
        }
    }
});

// Verify remaining files
const remaining = fs.readdirSync(avatarDir);
console.log(`Remaining files count: ${remaining.length}`);
console.log('Sample remaining files:', remaining.slice(0, 20));
